# Generated by Django 5.0.6 on 2024-05-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sport_person_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
            ],
        ),
    ]
